language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t gilwong00/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gilwong00/docker-react npm run test -- --coverage
