FROM node:alpine as builder

WORKDIR '/app'

COPY package.json ./
RUN yarn
COPY ./ ./
RUN yarn build

FROM nginx
# copies build folder generated by builder phase into ngnix folder
COPY --from=builder /app/build /usr/share/nginx/html

# the default command of the nginx container is to start the server so we don't need to specific a start command